apiVersion: 1

datasources:
  - name: CloudWatch
    type: cloudwatch
    uid: CloudWatch
    access: proxy
    jsonData:
      authType: credentials
      defaultRegion: us-east-1
    secureJsonData:
      accessKey: ${AWS_ACCESS_KEY_ID}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    isDefault: true
    editable: true

